# frozen_string_literal: true

require "state_machines"

require_relative "agent/accounting"
require_relative "agent/budget"
require_relative "agent/loop_machine"
require_relative "agent/model_caller"
require_relative "agent/tool_runner"
require_relative "agent/transition_listener"
require_relative "channel"
require_relative "context"
require_relative "effect"
require_relative "error"
require_relative "handler"
require_relative "middleware"
require_relative "response"
require_relative "store"
require_relative "timeline"
require_relative "toolset"
require_relative "workspace"

module Lain
  # The loop, written as an explicit state machine rather than a while-loop with
  # a stack of conditionals.
  #
  # The difference is not stylistic. Every `stop_reason` the wire can carry must
  # have somewhere to go, and a `case` with no `else` is how a new enum value --
  # or a forgotten old one like `:stop_sequence` -- becomes a turn that silently
  # does nothing. Here each reason is a named transition and {StopReason::UNKNOWN}
  # is a real destination, so an unrecognized value fails loudly instead of
  # falling through.
  #
  # The Agent owns the loop. Both SDKs offered to own it (`tool_runner`,
  # `Chat#complete`) and both were declined, because the loop is what this project
  # exists to study.
  class Agent
    # The state machine -- states, legal transitions, and the journaling seam --
    # is declared in {LoopMachine} and mixed in here. It also defines {STATES}.
    include LoopMachine

    # Kept for callers that rescue the harness's own halt. See Agent::Budget.
    BudgetExceeded = Budget::Exceeded

    attr_reader :timeline, :toolset, :context, :workspace,
                :iterations, :failure_reason, :budget

    # Delegated to {ModelCaller}, which now owns the provider alongside the
    # model phase's own middleware -- see #call_model.
    def provider = @model_caller.provider

    # Delegated to {Accounting}, which owns the run's token roll-up.
    def usage = @accounting.usage

    # @param journal [#<<] where per-turn usage records land; the Null channel
    #   by default. Today ONLY {Event::TurnUsage} is written here -- it is not
    #   yet the full run record.
    def initialize(provider:, toolset:, context:,
                   handler: nil,
                   timeline: nil,
                   workspace: Workspace.empty,
                   budget: Budget.new,
                   journal: Channel::Null.instance,
                   transition_listener: TransitionListener::Null,
                   model_middleware: Middleware::Stack.new,
                   tool_middleware: Middleware::Stack.new,
                   turn_middleware: Middleware::Stack.new)
      super() # state_machines sets the initial state through the super chain.
      @model_caller = ModelCaller.new(provider: provider, middleware: model_middleware)
      @toolset = toolset
      @context = context
      @timeline = timeline || Timeline.empty(store: Store.new)
      @workspace = workspace
      @budget = budget
      @turn_middleware = turn_middleware
      @tool_runner = build_tool_runner(handler, toolset, tool_middleware)
      seed_run_state(transition_listener, journal)
    end

    # Append a user turn and run until the loop settles.
    #
    # A new user turn reopens a settled loop, so asking again after `:done` (or
    # `:failed`) continues the conversation rather than raising on `dispatch!`
    # from a terminal state. The guard keeps the very first `ask` transition-free.
    #
    # @return [Lain::Response] the final assistant response
    def ask(text)
      reopen! unless awaiting_user?
      @timeline = @timeline.commit(role: :user, content: [{ "type" => "text", "text" => text }])
      run
    end

    # Drive the machine from its current Timeline. Separated from {#ask} so a
    # rewound or forked Timeline can be resumed without inventing a user turn.
    # The turn phase's env is deliberately minimal: `iteration` is the count of
    # turns already committed (0 for the very first), and `timeline` is the
    # Timeline as of the START of this turn -- the node a future speculative-
    # fork middleware would fork from, before this turn's own commit lands. The
    # block adds `:response`/`:settled` on the way back out, the same in/out
    # shape #call_model uses for `:request`/`:response`. This is the seam for
    # the future budget/iteration-ceiling/interrupt-hook/speculative-fork point
    # -- placing it, not building those features yet.
    def run
      @failure_reason = nil

      loop do
        env = @turn_middleware.call({ iteration: @iterations, timeline: @timeline }) do |inner|
          response = step
          inner.merge(response: response, settled: transition(response) == :settled)
        end
        return env.fetch(:response) if env.fetch(:settled)
      end
    end

    # `#done?` and `#failed?` are generated by the state machine, one predicate
    # per state, so they cannot disagree with the declared state set.

    # Time travel: the loop can be resumed from any earlier turn, which is what
    # makes speculative branching possible once a grader exists.
    def rewind(count = 1)
      @timeline = @timeline.rewind(count)
      reopen!
      self
    end

    private

    def build_tool_runner(handler, toolset, middleware)
      ToolRunner.new(handler: handler || Handler::Live.new(toolset: toolset), middleware: middleware)
    end

    # Seeds the mutable run context: a fresh Accounting rolling up over the
    # injected journal, and the observer the machine announces transitions to.
    # State itself is owned by the machine (initial: :awaiting_user). Called
    # once, at construction; the Accounting is what captures the journal.
    def seed_run_state(transition_listener, journal)
      @transition_listener = transition_listener
      @accounting = Accounting.new(journal: journal)
      @iterations = 0
      @failure_reason = nil
    end

    # One turn: bound, count, ask the model, account, record. Extracted from #run
    # so the loop reads as what it is -- iterate until the machine settles.
    def step
      @budget.check_iterations!(@iterations)
      @iterations += 1
      response = call_model
      # Correctness gate 1: commit the FULL content -- text, thinking, AND
      # tool_use blocks. Extracting only the text corrupts the very next turn.
      @timeline = @timeline.commit(role: :assistant, content: response.content)
      # Commit BEFORE the token check: a turn that busts the ceiling was still
      # paid for, so it stays in the record -- Timeline and Journal both --
      # rather than vanishing with the raise.
      @budget.check_tokens!(@accounting.observe(response, digest: @timeline.head_digest))
      response
    end

    # Every stop_reason the wire can carry gets a named destination here, and the
    # `else` catches whatever the enum grows next.
    #
    # @return [Symbol] :settled when the loop is finished, :continue otherwise
    def transition(response)
      case response.stop_reason
      when StopReason::TOOL_USE then perform_tools(response)
      when StopReason::END_TURN, StopReason::STOP_SEQUENCE then succeed
      when StopReason::PAUSE_TURN then resume_paused
      when StopReason::MAX_TOKENS then fail_with("model hit max_tokens before finishing")
      when StopReason::REFUSAL then fail_with("model refused to continue")
      when StopReason::UNKNOWN then fail_with("unrecognized stop_reason from provider")
      else fail_with("unhandled stop_reason #{response.stop_reason.inspect}")
      end
    end

    def succeed
      complete!
      :settled
    end

    def fail_with(reason)
      @failure_reason = reason
      fail_run!
      :settled
    end

    # A paused turn means a server-side tool is mid-flight; the correct response is
    # to send the conversation back unchanged and let the server continue. It
    # counts against max_iterations, so a provider that pauses forever still stops.
    def resume_paused
      pause!
      :continue
    end

    def call_model
      dispatch!
      request = @context.render(timeline: @timeline, toolset: @toolset, workspace: @workspace)
      @model_caller.call(request)
    end

    # Correctness gate 2: every tool_result for one assistant turn goes back in
    # ONE user message. Splitting them across messages silently teaches Claude to
    # stop making parallel tool calls -- a regression with no error attached.
    def perform_tools(response)
      use_tools!
      @timeline = @timeline.commit(role: :user, content: @tool_runner.run(response, context: self))
      :continue
    end
  end
end
