# frozen_string_literal: true

require "time"
require "fileutils"
require "shellwords"

module Lain
  module CLI
    module Command
      # `/meta` (T23): generate a customized harness from a prompt, then -- only
      # on an explicit `/meta run <slug>` -- launch it in a new tmux window.
      #
      # The generate/run split IS the safety line. A generated script runs with
      # the user's full authority, so `/meta <prompt>` never executes anything:
      # it drives the read-only `meta_harness` role ({Skill::RoleSpawn}, `:inherit`
      # context) to assemble a plain lain-API script, writes it to
      # `.lain/meta/<slug>.rb` (the `.lain/` artifact home, like state.json), and
      # returns the path plus a summary. The window opens ONLY when the human
      # comes back and types the run verb -- generation and execution are two
      # deliberate steps, never one.
      #
      # The written script is honest by construction: this command owns its
      # header (naming the origin prompt and the head digest it was generated at)
      # and its `require "lain"`, so provenance never rests on the model's
      # goodwill. The role assembles the body; the command frames it.
      #
      # `/meta summarizer <prompt>` (A4) aims that same generate-then-review
      # discipline at a {Summarizer} declaration instead of a harness. It writes
      # `.lain/summarizers/<slug>.rb` -- deliberately NOT the `.lain/meta/` the
      # run verb indexes, so a summarizer can never be launched as a script. A
      # summarizer is loaded by {Summarizer::Catalog} from `.lain/summarizers.rb`
      # after a human has read the declaration and wired it in; /meta writes the
      # file and stops there, and nothing auto-includes it.
      class Meta
        # What one generate produces. The two generate verbs differ ONLY in
        # these -- which read-only role assembles the body, where the reviewable
        # file lands, how the header says what the file IS, what the human is
        # told to do next, and the slug to fall back on when a prompt reduces to
        # nothing -- so they run ONE code path. A second copy of that path would
        # be a second place for the generate-then-review line to drift.
        Artifact = Data.define(:role, :dir, :banner, :preface, :advice, :fallback)

        HARNESS = Artifact.new(
          role: :meta_harness,
          dir: File.join(".lain", "meta"),
          banner: ["GENERATED by /meta -- a customized harness. REVIEW before running;",
                   "/meta only writes this file, it never runs generated code."].freeze,
          preface: %(require "lain"),
          advice: "review it, then launch it in a new tmux window with:\n  /meta run %<slug>s",
          fallback: "harness"
        )

        # A summarizer is DATA for {Summarizer::Builder}, not a script: it lands
        # outside {HARNESS}'s directory precisely so `/meta run` cannot resolve
        # it, and it carries no `require "lain"` because nothing ever executes
        # the file. NOTHING reads this directory either -- {Summarizer::Catalog}
        # loads the single file `.lain/summarizers.rb` -- so the header and the
        # reply both have to say so, because Ruby's own `foo.rb` + `foo/`
        # convention says the opposite and a reader will assume auto-loading.
        DECLARATION = Artifact.new(
          role: :meta_summarizer,
          dir: File.join(".lain", "summarizers"),
          banner: ["GENERATED by /meta -- a summarizer declaration, NOT a script.",
                   "NOTHING loads this directory: REVIEW this file, then COPY the declaration",
                   "into .lain/summarizers.rb yourself. /meta neither loads nor runs it."].freeze,
          preface: "",
          advice: "review it, then COPY the declaration into .lain/summarizers.rb -- nothing loads " \
                  ".lain/summarizers/, and %<slug>s is not a /meta run slug",
          fallback: "summarizer"
        )

        # The role is told to answer with ONE fenced ruby block, and models do.
        # The fence is WIRE FORMAT, not file content: written through, it makes
        # every generated file a SyntaxError -- fatal here, because a declaration
        # that {Summarizer::Builder} cannot load is the whole value of the verb.
        # Prose around the block goes with it. A body with no fence is written
        # verbatim, which is what keeps the harness path byte-identical.
        FENCE = /^```[a-z]*[ \t]*\n(.*?)^```[ \t]*$/m

        # A well-formed slug, exactly what {#slugify} emits: a `run <slug>` that
        # does not match is refused before it can index a file, so the launch
        # verb can never resolve a path outside {HARNESS}'s directory.
        SLUG = /\A[a-z0-9-]+\z/

        # The launch keyword. A prompt whose first word is literally "run" is
        # read as a launch (documented in {#usage}); write "/meta launch a run
        # loop" as, e.g., "/meta a run loop" if that collides. {SUMMARIZER}
        # shadows its first word the same way.
        RUN = "run"
        SUMMARIZER = "summarizer"

        USAGE = "/meta <prompt> -- generate a customized harness script (review it, then /meta run <slug>); " \
                "/meta summarizer <prompt> -- generate a summarizer declaration to review"

        def initialize(root: Dir.pwd)
          @root = root
          freeze
        end

        def name = "meta"

        def usage = USAGE

        # Three verbs behind one command: `run <slug>` launches an existing
        # script, `summarizer <prompt>` generates a summarizer declaration, and
        # anything else is a harness prompt. Splitting on the first word keeps
        # the whole remaining prompt intact for generation.
        def call(args, env)
          keyword, rest = args.to_s.strip.split(/\s+/, 2)
          return launch(rest.to_s.strip, env) if keyword == RUN
          return generate(DECLARATION, rest.to_s.strip, env) if keyword == SUMMARIZER

          generate(HARNESS, args.to_s.strip, env)
        end

        private

        # Generate NEVER runs code: it spawns the read-only role, frames its
        # body into an honest file, writes it, and hands back the path.
        def generate(artifact, prompt, env)
          return USAGE if prompt.empty?

          result = env.role_spawn.call(artifact.role, :inherit, prompt)
          return generation_failed(artifact, result) if result.error?

          contents = compose(artifact, body: body_of(result), prompt:,
                                       digest: env.agent.timeline.head_digest)
          slug = slugify(artifact, prompt)
          generated(artifact, write(artifact, slug, contents), slug)
        end

        # The ONLY path that executes a generated script -- an explicit run verb,
        # against a file the human has had the chance to read.
        def launch(slug, env)
          return USAGE if slug.empty?
          # The run slug indexes into `.lain/meta/`; validate it against the
          # SAME charset #slugify emits BEFORE it reaches File.join, or a slug
          # like `../../etc/whatever` traverses out of the artifact home and
          # `run` launches an arbitrary .rb anywhere on disk (Shellwords.escape
          # stops shell injection, not path traversal).
          return bad_slug(slug) unless slug.match?(SLUG)

          # HARNESS, spelled out: the run verb resolves inside the harness home
          # and nowhere else, so no slug can reach a generated DECLARATION.
          path = artifact_path(HARNESS, slug)
          return no_script(slug, path) unless File.exist?(path)

          place(env, slug, path)
        end

        def place(env, slug, path)
          command = "#{RbConfig.ruby} #{Shellwords.escape(path)}"
          placement = env.tmux_surface.window(command:, name: "meta-#{slug}", cwd: @root)
          "launched #{path} in tmux #{placement.kind} #{placement.target}"
        rescue TmuxSurface::TmuxUnavailable => e
          "#{e.message}\nrun it yourself: ruby #{path}"
        end

        def write(artifact, slug, contents)
          path = artifact_path(artifact, slug)
          FileUtils.mkdir_p(File.dirname(path))
          File.write(path, contents)
          path
        end

        def artifact_path(artifact, slug) = File.join(@root, artifact.dir, "#{slug}.rb")

        # The command owns the header and the preface, so a generated file is
        # honest whatever the model returned: the origin prompt and head digest
        # are named at the top, and a harness's `require "lain"` is guaranteed
        # present. A declaration has no preface -- nothing loads it as a script
        # -- and dropping the empty part is what keeps the blank lines even.
        def compose(artifact, body:, prompt:, digest:)
          [header(artifact, prompt, digest), artifact.preface, body].reject(&:empty?).join("\n\n")
        end

        def header(artifact, prompt, digest)
          (["# frozen_string_literal: true", "#"] +
            artifact.banner.map { |line| "# #{line}" } + ["#"] + prompt_lines(prompt) +
            ["# head digest:   #{digest || "(none)"}",
             "# generated at:  #{Time.now.utc.iso8601}"]).join("\n")
        end

        # A multi-line prompt stays whole in the header, each line commented so
        # the file still parses; only the first line carries the label.
        def prompt_lines(prompt)
          lines = prompt.split("\n")
          ["# origin prompt: #{lines.first}"] + lines.drop(1).map { |line| "#                #{line}" }
        end

        # The bytes the command frames: the role's text, with its {FENCE} taken
        # off. `|| body` is the match-or-whole idiom, not a nil guard on a
        # collaborator -- an unfenced body IS the body.
        def body_of(result) = unfence(text_of(result))

        def unfence(body) = body[FENCE, 1] || body

        # The role answers with a String body; an Array of content blocks is
        # flattened to its text so the file stays plain ruby either way.
        def text_of(result)
          content = result.content
          content.is_a?(String) ? content : content.filter_map { |block| block["text"] }.join("\n")
        end

        # A slug the human can type back: the prompt reduced to its leading
        # words. A prompt that reduces to nothing falls back to the artifact's
        # own name, so `/meta summarizer !!!` cannot land on a harness slug.
        def slugify(artifact, prompt)
          words = prompt.downcase.gsub(/[^a-z0-9]+/, " ").split.first(6)
          words.empty? ? artifact.fallback : words.join("-")
        end

        def generated(artifact, path, slug)
          "wrote #{path}\n\n#{format(artifact.advice, slug:)}"
        end

        def generation_failed(artifact, result)
          "#{artifact.role} could not generate: #{body_of(result)}"
        end

        def no_script(slug, path)
          "no script #{slug.inspect} has been generated (#{path} does not exist) -- " \
            "generate one first with /meta <prompt>"
        end

        def bad_slug(slug)
          "not a valid script name: #{slug.inspect} -- a slug is lowercase letters, digits, and dashes " \
            "(the name /meta printed when it wrote the script)"
        end
      end
    end
  end
end
