# frozen_string_literal: true

require_relative "lain/version"
require_relative "lain/error"
require_relative "lain/canonical"
require_relative "lain/turn"
require_relative "lain/store"
require_relative "lain/timeline"
require_relative "lain/event"
require_relative "lain/channel"
require_relative "lain/sink"
require_relative "lain/usage"
require_relative "lain/request"
require_relative "lain/response"
require_relative "lain/tool"
require_relative "lain/toolset"
require_relative "lain/effect"
require_relative "lain/middleware"
require_relative "lain/handler"
require_relative "lain/handler/approving"
require_relative "lain/handler/live"
require_relative "lain/handler/mock"
require_relative "lain/tools"
require_relative "lain/provider"
require_relative "lain/provider/anthropic"
require_relative "lain/provider/anthropic_raw"
require_relative "lain/provider/http"
require_relative "lain/provider/mock"
require_relative "lain/workspace"
require_relative "lain/context"
require_relative "lain/agent"
require_relative "lain/frontend"
require_relative "lain/journal"
require_relative "lain/price_book"
require_relative "lain/ledger"
require_relative "lain/capability"
require_relative "lain/grader"
require_relative "lain/grader/fixture"
require_relative "lain/grader/rubric"
require_relative "lain/compare"
require_relative "lain/bench/dry_replay"
require_relative "lain/bench/live_replay"
require_relative "lain/bench/speculative"

# The compiled Rust extension. Defines Lain.hello and Lain::Ext.init_tracing.
require "lain/lain"

# An agent harness built as a study bench: context strategies, tool designs, and
# orchestration tactics are swappable, observable, and comparable.
module Lain
end
