# frozen_string_literal: true

require "prism"
require "pathname"

# Mechanical guard against ONE consequence of using this repository as a spec
# fixture: an example that only exists because a file does.
#
# The post-mortem is in `spec/lain/gherkin_spec.rb` and `bin/lint-gherkin-docs`.
# A spec globbed `planning/specs/*.md` and minted one example per document, so
# writing a plan doc could turn `rake pspec` red for everyone -- and, the part
# this file exists for, ADDING one moved the suite's example count. That count
# is the number CLAUDE.md tells every reader to compare against a serial run to
# detect a worker that died mid-parallel-run, because `parallel_tests` reports
# only the examples that SURVIVED. A count that drifts with the contents of
# `docs/`, `planning/` or the shipped skill tree cannot do that job.
#
# == What is forbidden, and what deliberately is not
#
# Forbidden: an example -- or a shared group carrying examples -- brought into
# being by a scan of this repository's own tree. Two routes, and both are here
# because only the first is obvious:
#
#   Dir.glob(...).each { |path| it("...") { } }           # a loop MINTS examples
#   it_behaves_like "a contract", corpus: Dir.glob(...)   # the SHARED GROUP loops
#
# NOT forbidden: reading repository files INSIDE an example. That is what
# `spec/output_discipline_spec.rb`, `spec/docs_naming_spec.rb`,
# `spec/lain/agent_state_machine_diagram_spec.rb`, `spec/lain/review/bounds_spec.rb`
# and `spec/lain/epic/scribe_write_side_spec.rb` all do, and in every one of them
# lain's own artifact IS the subject. One example iterating a thousand files is a
# fixed contribution to the count and a single failure a reader can act on; a
# thousand examples is neither. The line this file draws is exactly there.
#
# Nor is a loop over a LITERAL forbidden. `spec/lain/survey/chunker/code_spec.rb`
# iterates a hand-written `%w[...]` of repository paths: it reads repo content,
# which is a fixture-quality question for a human, but its count is a property of
# the list and not of the tree.
#
# Structure, not text: Prism gives the syntax tree, so a `Dir.glob` named in a
# comment or a heredoc is never mistaken for one that runs, and the scan has to
# be the thing the loop actually iterates.
module RepoAsFixture
  SPEC_ROOT = Pathname(__dir__)

  # Anything that defines an example when called.
  EXAMPLE_METHODS = %w[it specify example scenario its
                       fit fspecify fexample xit xspecify xexample].freeze

  # Blocks that merely NEST. An example inside one of these is not generated by
  # it -- the enclosing group is where the question is asked.
  GROUP_METHODS = %w[describe context feature
                     fdescribe fcontext xdescribe xcontext
                     shared_examples shared_examples_for shared_context
                     before after around let let! subject].freeze

  # Calls that pull in a group whose OWN loop mints one example per element.
  INCLUSION_METHODS = %w[it_behaves_like it_should_behave_like
                         include_examples include_context].freeze

  # Directory reads, and only unambiguous ones. `Find.find` is deliberately
  # absent: `Enumerable#find` shares the name and is everywhere, and precision
  # matters more here than covering a route `spec/` does not use.
  SCAN_METHODS = %w[glob children entries each_child each_entry].freeze

  # `Dir[...]` is `Dir.[]` -- and so is `hash["key"]`, `ENV["CASES"]` and
  # `JSON.parse(body)["rows"]`. The subscript is therefore admitted ONLY on the
  # two constants that read directories. Without that, every string-keyed
  # subscript is a "repository scan", which fires hardest on the data-driven
  # spec-owned-fixture shape this file's own failure message recommends.
  SUBSCRIPT_RECEIVERS = %w[Dir Pathname].freeze

  # A path expression anchored at the spec file -- or at the directory the suite
  # is run from -- is anchored at this repository; a fixture built under
  # `Dir.mktmpdir` is not, and that is the whole distinction. `__FILE__` parses
  # to its own node type, `__dir__` and `Dir.pwd` to calls.
  ANCHOR_METHODS = %w[__dir__ pwd].freeze

  # A scan given a bare String LITERAL is anchored too. The reason to care is
  # the RELATIVE spelling: `Dir.glob("planning/specs/*.md")` is a character
  # shorter than the `__dir__` form, it works because the suite runs from the
  # repository root, and it is exactly how the `gherkin_spec.rb` violation would
  # come back.
  #
  # Being honest about the reach, since a comment that stopped being true is
  # this file's own subject. The literal is required to be the WHOLE path
  # argument, so `File.join(tmp, "*.rb")` stays out -- but "a literal can only
  # mean the repository" is NOT a guarantee, and two shapes prove it:
  # `Dir.glob("**/*", base: File.join(tmp, ".git"))` re-anchors a literal onto a
  # temporary directory (`workspace/snapshot/scope/shadow_git_spec.rb` writes
  # exactly that), and `Dir.children("/proc/self/fd")` names something outside
  # any repository at all. The `base:` form is excluded below because it is
  # genuinely misdiagnosed. The absolute-elsewhere form is deliberately left
  # flagged: a count minted per entry of `/proc/self/fd` is less stable than one
  # minted per file in `docs/`, so the verdict is right even though the word
  # "repository" is not.
  #
  # KNOWN LIMITATIONS, among them -- demonstrated rather than assumed, and NOT
  # an exhaustive list:
  #
  #   * The name closure below is PER FILE, so a scan held in `spec/support/`
  #     and iterated from a spec file is not seen -- `ToolRegistry.shipped_names`
  #     is exactly that shape (it is used inside an example today, which is why
  #     it is not a violation).
  #   * The closure is also FLAT and unscoped, so a local name reused for both a
  #     literal and a scan resolves to whichever was written last. That is the
  #     one shape known to yield a false POSITIVE rather than a miss.
  #   * A path assembled at runtime from something this file cannot see -- an
  #     ENV var, a value read from a file -- carries no anchor and no literal.
  #
  # These are holes in the rule's REACH. Its verdicts are sound for every shape
  # tested, with the flat-closure case above as the known exception.

  # One flagged site, with enough to go and look at it.
  Violation = Struct.new(:path, :line, :snippet) do
    def to_s = "#{path}:#{line} -> #{snippet}"
  end

  # Walks one spec file's syntax tree.
  # Depth-first over a Prism tree. Its own module because both objects below
  # walk one, and neither of them is about walking.
  module Walk
    module_function

    def each_node(node, &block)
      return to_enum(:each_node, node) unless block_given?
      return unless node.is_a?(Prism::Node)

      yield node
      node.compact_child_nodes.each { |child| each_node(child, &block) }
    end
  end

  # ONE question, asked of any expression in one file: does evaluating this
  # READ A DIRECTORY TREE? Everything about anchors, literals and name
  # resolution lives here, so {Scanner} below is only ever about where examples
  # are minted.
  class Sources
    include Walk

    def initialize(root)
      @anchored = []
      @rooted = []
      defined = definitions(root)
      grow_anchored(defined)
      grow_rooted(defined)
    end

    # A shell-out counts whatever it runs (`git ls-files`, `nproc`): a count
    # derived from a subprocess is no more stable than one derived from a glob.
    def reads_tree?(node)
      each_node(node).any? do |inner|
        (scan_call?(inner) && (anchored?(inner) || literal_path?(inner))) ||
          subprocess?(inner) || rooted_read?(inner)
      end
    end

    def subprocess?(node) = each_node(node).any?(Prism::XStringNode)

    private

    # `name => the expression it was defined from`, for the shapes a spec file
    # uses to hold a scan: a constant, a local, and a `def` returning one.
    def definitions(root)
      each_node(root).with_object({}) do |node, found|
        case node
        when Prism::ConstantWriteNode, Prism::ConstantPathWriteNode,
             Prism::LocalVariableWriteNode,
             Prism::InstanceVariableWriteNode, Prism::ClassVariableWriteNode
          found[write_name(node)] = node.value
        when Prism::DefNode
          found[node.name.to_s] = node.body
        end
      end
    end

    # Both properties travel by NAME as well as by expression: `ROOT =
    # Pathname(__dir__)` makes `ROOT` anchored, and `DOCS = ROOT.glob(...)` then
    # makes `DOCS` rooted, three statements from the only `__dir__` in the file.
    # So each is a fixed point over the definitions rather than one walk --
    # iterated because a definition may be written above the one it depends on.
    #
    # Each predicate reads the set being built, so the set is PUBLISHED every
    # round rather than returned at the end.
    def grow_anchored(defined)
      @anchored += (grown = ungrown(defined, @anchored) { |value| anchored?(value) }) until grown&.empty?
    end

    def grow_rooted(defined)
      @rooted += (grown = ungrown(defined, @rooted) { |value| reads_tree?(value) }) until grown&.empty?
    end

    def ungrown(defined, known, &predicate)
      defined.except(*known).select { |_, value| yield(value) }.keys
    end

    # The WHOLE path argument spelled as a literal, and not re-anchored: a
    # `base:` keyword makes the literal relative to somewhere else entirely,
    # which is how a tmpdir sweep gets spelled as a constant string.
    def literal_path?(call)
      arguments = call.arguments&.arguments
      arguments&.first.is_a?(Prism::StringNode) && !rebased?(arguments)
    end

    def rebased?(arguments)
      arguments.grep(Prism::KeywordHashNode)
               .flat_map(&:elements)
               .any? { |pair| pair.is_a?(Prism::AssocNode) && key_name(pair.key) == "base" }
    end

    def key_name(key) = key.is_a?(Prism::SymbolNode) ? key.value.to_s : nil

    def scan_call?(node)
      case node
      when Prism::CallNode
        node.name.to_s == "[]" ? directory_constant?(node.receiver) : SCAN_METHODS.include?(node.name.to_s)
      else
        false
      end
    end

    def directory_constant?(receiver)
      receiver.is_a?(Prism::ConstantReadNode) && SUBSCRIPT_RECEIVERS.include?(receiver.name.to_s)
    end

    def anchored?(node)
      each_node(node).any? do |inner|
        inner.is_a?(Prism::SourceFileNode) ||
          (inner.is_a?(Prism::CallNode) && ANCHOR_METHODS.include?(inner.name.to_s)) ||
          @anchored.include?(read_name(inner))
      end
    end

    def rooted_read?(node) = @rooted.include?(read_name(node))

    # Namespaced and bare constants answer the same name, which is what lets
    # `DeletionMap::ROOT` resolve to the `ROOT =` written inside that module.
    # `spec/lain/review/deletability_spec.rb` builds exactly that pair.
    def write_name(node)
      node.is_a?(Prism::ConstantPathWriteNode) ? node.target.name.to_s : node.name.to_s
    end

    def read_name(node)
      case node
      when Prism::ConstantReadNode, Prism::ConstantPathNode,
           Prism::LocalVariableReadNode,
           Prism::InstanceVariableReadNode, Prism::ClassVariableReadNode
        node.name.to_s
      when Prism::CallNode
        node.name.to_s if node.receiver.nil? && node.arguments.nil? && node.block.nil?
      end
    end
  end

  # Where one spec file MINTS examples, asking {Sources} what each loop is over.
  class Scanner
    include Walk

    def initialize(path)
      @path = path
    end

    # @param source [String] the whole spec file
    # @return [Array<Violation>]
    def scan(source)
      result = Prism.parse(source)
      # `.value` is a ProgramNode even for unparseable bytes, so `.failure?` is
      # the only question that can answer "was this really read?".
      raise "could not parse #{@path}" if result.failure?

      root = result.value
      @sources = Sources.new(root)
      (generated_examples(root) + scan_derived_inclusions(root)).uniq
    end

    private

    # Every call carrying a block, paired with the ancestors it sits under, so
    # an example can ask what it is nested inside.
    def call_stack(root)
      each_node(root).with_object({}) do |node, stacks|
        node.compact_child_nodes.each { |child| stacks[child] = (stacks[node] || []) + [node] }
      end
    end

    def generated_examples(root)
      stacks = call_stack(root)
      each_node(root).select { |node| minting_call?(node) }.flat_map do |example|
        iterators(stacks.fetch(example, [])).select { |call| @sources.reads_tree?(call.receiver) }
                                            .map { |call| violation(example, call) }
      end
    end

    # An inclusion counts as minting here as well as below, because the two
    # routes COMPOSE: a `it_behaves_like` inside a loop over a scan mints
    # (corpus x group) examples, and neither route alone sees it.
    def minting_call?(node)
      (node.is_a?(Prism::CallNode) && EXAMPLE_METHODS.include?(node.name.to_s) && !node.block.nil?) ||
        inclusion_call?(node)
    end

    # The enclosing calls that ITERATE -- a block-bearing call with a receiver
    # that is not one of RSpec's own nesting methods.
    def iterators(stack)
      stack.select { |node| node.is_a?(Prism::CallNode) && !node.block.nil? && !node.receiver.nil? }
           .reject { |node| GROUP_METHODS.include?(node.name.to_s) }
    end

    # The other route: the loop lives in the shared group, so the corpus handed
    # to it is what decides how many examples exist.
    def scan_derived_inclusions(root)
      each_node(root).select { |node| inclusion_call?(node) && @sources.reads_tree?(node.arguments) }
                     .map do |node|
                       Violation.new(@path, node.location.start_line,
                                     "#{node.name} handed a repository scan")
                     end
    end

    def inclusion_call?(node)
      node.is_a?(Prism::CallNode) && INCLUSION_METHODS.include?(node.name.to_s) && !node.arguments.nil?
    end

    def violation(example, iterator)
      Violation.new(@path, example.location.start_line,
                    "#{example.name} minted per element of #{source_of(iterator.receiver)} (##{iterator.name})")
    end

    # Named apart because the remedy differs: a scan is pinned by listing the
    # files, a subprocess by not asking the machine a question at load time.
    def source_of(receiver)
      @sources.subprocess?(receiver) ? "a subprocess's output" : "a repository scan"
    end
  end

  module_function

  # @return [Array<Pathname>] every spec file the report is derived from
  def spec_files = SPEC_ROOT.glob("**/*.rb").sort

  # @return [Array<Violation>] every flagged site under `spec/`
  def violations
    spec_files.flat_map do |file|
      Scanner.new(file.relative_path_from(SPEC_ROOT).to_s).scan(file.read)
    end
  end
end

# The examples below iterate `spec/` INSIDE an example rather than around one,
# which is the rule this file states. Its own count is four, whatever the tree
# holds -- and that is the point.
RSpec.describe "the repository is not a spec fixture" do
  it "has no example generated from a scan of repository content" do
    # The non-vacuity half, and it is not decoration: an empty report is the
    # SAME observation as a scanner that read nothing, and this file's whole
    # subject is assertions that cannot fail. The block this guard replaced
    # (`gherkin_spec.rb`, removed in 68df3188) opened with `it "has a corpus to
    # check"` for exactly this reason, and that assertion did not survive the
    # move until it was put back here.
    expect(RepoAsFixture.spec_files.size).to be > 500

    violations = RepoAsFixture.violations

    expect(violations).to be_empty, lambda {
      listing = violations.map { |violation| "  #{violation}" }.join("\n")
      "These examples exist only because a repository file does, so the suite's " \
        "example count moves with the tree and stops detecting a dead parallel " \
        "worker. Iterate the scan INSIDE one example; name the files in a " \
        "literal roster (a `spec/fixtures/**` sweep counts as a scan too); or " \
        "move the check to a `bin/lint-*` script under pre-commit the way " \
        "`bin/lint-gherkin-docs` was moved. A count minted per element of a " \
        "SUBPROCESS's output is the same defect from a different cause -- there " \
        "the fix is to stop asking the machine a question while examples are " \
        "being defined. Found:\n#{listing}"
    }
  end

  # Guards the guard: the shapes this must and must not flag, as literal source,
  # so a rule that quietly stopped matching is a red example rather than an
  # empty report.
  describe "the scanner itself" do
    def flagged(source) = RepoAsFixture::Scanner.new("self_test").scan(source)

    it "flags an example minted per repository file, however the scan is spelled" do
      minted = [
        %(Dir.glob(File.expand_path("../docs/*.md", __dir__)).each { |doc| it("reads \#{doc}") { } }),
        %(Dir[File.expand_path("../planning/*.md", __dir__)].each { |doc| it("x") { } }),
        %(DOCS = Pathname(__dir__).glob("../docs/**/*.md")\nDOCS.each { |doc| context(doc) { it("x") { } } }),
        %(ROOT = Pathname(__FILE__)\nfiles = ROOT.children\nfiles.each { |f| specify("x") { } }),
        %(Dir.children(File.join(Dir.pwd, "planning")).each { |doc| it("x") { } }),
        # A namespaced constant, the shape `deletability_spec.rb` builds today.
        %(module Map\n  ROOT = Pathname(__dir__)\nend\n) +
          %(SOURCES = Dir[Map::ROOT.join("lib/**/*.rb")]\nSOURCES.each { |f| it("x") { } }),
        # A RELATIVE literal: shorter than the anchored form, works because the
        # suite runs from the repository root, and the likeliest way the
        # `gherkin_spec.rb` violation comes back.
        %(Dir.glob("planning/specs/*.md").each { |doc| it("x") { } }),
        %(Pathname.glob("docs/**/*.md").each { |doc| it("x") { } }),
        %(Dir.glob("/abs/lain/docs/*.md").each { |doc| it("x") { } }),
        %(`git ls-files planning`.lines.each { |doc| it("x") { } }),
        # The two routes COMPOSED: the loop is here, the examples are in the
        # shared group.
        %(Dir.glob(File.expand_path("../lib/**/*.rb", __dir__)).each { |f| it_behaves_like("a chunker", f) }),
        %(it_behaves_like "a chunker", corpus: Dir.glob(File.expand_path("../../lib/**/*.rb", __dir__)))
      ]

      expect(minted.map { |source| flagged(source).size }).to eq([1] * 12)
    end

    it "does not flag a repository scan performed inside an example" do
      source = <<~RUBY
        it "has no terminal writes" do
          expect(Pathname(__dir__).glob("../lib/**/*.rb").flat_map { |f| scan(f) }).to be_empty
        end
      RUBY

      expect(flagged(source)).to be_empty
    end

    it "does not flag a loop over a literal, or a scan of a directory this repository does not own" do
      source = <<~RUBY
        %w[lib/lain/version.rb lib/lain/error.rb].each do |relative|
          it("holds to the cap") { expect(units(relative).size).to be <= 1 }
        end
        Dir.mktmpdir do |tmp|
          Dir.glob(File.join(tmp, "*.rb")).each { |made| it("x") { } }
          Dir.glob("**/*", base: File.join(tmp, ".git")).each { |made| it("x") { } }
        end
      RUBY

      expect(flagged(source)).to be_empty
    end

    # `Dir[...]` is `Dir.[]`, and so is every string-keyed subscript in Ruby.
    # Reading a table and iterating it is the data-driven shape this file's own
    # failure message recommends, so flagging it would make the rule advise a
    # pattern it then refuses.
    it "does not flag an ordinary subscript that happens to spell Dir.[]" do
      source = <<~RUBY
        ENV["CASES"].split(",").each { |name| it("x") { } }
        CASES["rows"].each { |row| it("x") { } }
        YAML.load_file(path)["cases"].each { |row| it("x") { } }
        JSON.parse(body)["examples"].each { |row| it("x") { } }
        rows[:symbol_key].each { |row| it("x") { } }
      RUBY

      expect(flagged(source)).to be_empty
    end
  end
end
